version: '3'

services:
  test_shop:
    container_name: test_shop
    external_links:
      - db-test-pg:db-test-pg
    environment:
      - DB_HOST_TEST=db-test-pg
    networks:
      - shop_tests_network
    build:
      context: .
      dockerfile: Dockerfile_tests
    ports:
      - "8000:8000"
    depends_on:
        db_test:
          condition: service_healthy

  db_test:
    image: postgres:16-alpine
    container_name: db-test-pg
    environment:
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
    networks:
      - shop_tests_network
    command: -p ${DB_PORT_TEST}
    expose:
      - ${DB_PORT_TEST}

    healthcheck:
      test: pg_isready -U ${DB_USER_TEST} -p ${DB_PORT_TEST}
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  shop_tests_network:
    name: shop_tests_network
